import Link from "next/link";
import { ArrowRight, BatteryCharging, CalendarDays, Check, Clock3, HeartHandshake, Sparkles } from "lucide-react";
import { Brand } from "@/components/brand";

const steps = [
  { icon: BatteryCharging, title: "Check-in năng lượng", text: "Kéo một thanh nhỏ để nói hôm nay bạn đang ở mức nào." },
  { icon: CalendarDays, title: "Xếp lịch vừa sức", text: "Thấy trước mỗi việc sẽ lấy đi hay hồi lại bao nhiêu năng lượng." },
  { icon: HeartHandshake, title: "Lắng nghe sau mỗi việc", text: "Cập nhật cảm nhận thật để phần còn lại của ngày tự điều chỉnh." },
];

export default function Home() {
  return (
    <main className="overflow-hidden bg-cream-50">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Brand /><nav className="flex items-center gap-3"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-sm font-bold text-ink-700 hover:bg-sage-50 sm:block">Đăng nhập</Link><Link href="/login" className="button-primary px-4 py-2.5 text-sm">Bắt đầu ngay <ArrowRight size={16} /></Link></nav></header>
      <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:pb-28 lg:pt-24">
        <div><span className="eyebrow"><Sparkles size={14} /> Nhẹ nhàng hơn với chính mình</span><h1 className="mt-6 max-w-3xl text-5xl font-bold leading-[1.04] tracking-[-.045em] text-ink-900 sm:text-6xl lg:text-7xl">Sắp lịch theo <span className="relative text-sage-700">năng lượng</span>, không chỉ theo thời gian.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink-600 sm:text-xl">Biến lịch trình thành một người bạn biết lúc nào bạn sẵn sàng, lúc nào nên chậm lại và lúc nào cần một khoảng thở.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="button-primary px-6 py-3.5">Thử sắp một ngày <ArrowRight size={18} /></Link><a href="#cach-hoat-dong" className="button-secondary px-6 py-3.5">Xem cách hoạt động</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-ink-600"><span className="inline-flex items-center gap-2"><Check size={16} className="text-sage-700" />Không cần thẻ</span><span className="inline-flex items-center gap-2"><Check size={16} className="text-sage-700" />Có chế độ dùng thử</span></div></div>
        <div className="relative mx-auto w-full max-w-lg"><div className="absolute -left-12 top-20 size-40 rounded-full bg-amber-200/55 blur-3xl" /><div className="relative rotate-[1.5deg] rounded-[2rem] border border-sage-200 bg-white p-5 shadow-[0_30px_90px_rgba(35,61,50,.16)] sm:p-7"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-ink-500">Năng lượng hôm nay</p><p className="mt-1 text-3xl font-bold text-ink-900">75%</p></div><span className="grid size-12 place-items-center rounded-2xl bg-sage-100 text-sage-700"><BatteryCharging /></span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-sage-100"><div className="h-full w-3/4 rounded-full bg-sage-600" /></div><div className="mt-7 space-y-3"><Preview time="09:00" title="Tập trung làm việc" energy="75 → 60" color="bg-amber-100" /><Preview time="12:00" title="Ăn trưa và đi bộ" energy="60 → 75" color="bg-sage-100" /><Preview time="15:00" title="Học một điều mới" energy="75 → 65" color="bg-sky-100" /></div><div className="mt-6 flex items-center justify-between rounded-2xl bg-cream-100 p-4"><span className="text-sm text-ink-600">Cuối ngày dự kiến</span><strong className="text-xl text-sage-800">65%</strong></div></div></div>
      </section>
      <section className="border-y border-sage-100 bg-white py-20"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-8 lg:grid-cols-2 lg:items-center"><div><span className="eyebrow"><Clock3 size={14} /> Thời gian khác năng lượng</span><h2 className="mt-5 text-3xl font-bold tracking-tight text-ink-900 sm:text-4xl">Một ô trống trong lịch chưa chắc là một khoảng bạn đủ sức.</h2></div><div className="space-y-4 text-base leading-7 text-ink-600"><p>Lịch truyền thống hỏi: <strong className="text-ink-900">“Bạn còn giờ nào trống?”</strong></p><p>Chúng mình hỏi thêm: <strong className="text-sage-800">“Đến lúc đó, bạn còn bao nhiêu năng lượng?”</strong></p><p>Vì một ngày tốt không phải là ngày kín lịch — mà là ngày bạn hoàn thành điều quan trọng và vẫn còn là chính mình.</p></div></div></section>
      <section id="cach-hoat-dong" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Chỉ ba bước nhỏ</span><h2 className="mt-5 text-4xl font-bold tracking-tight text-ink-900">Một ngày được xếp theo cách bạn cảm nhận</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-[1.75rem] border border-sage-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-sage-100 text-sage-700"><Icon size={23} /></span><span className="text-sm font-bold text-sage-400">0{index + 1}</span></div><h3 className="mt-7 text-xl font-bold text-ink-900">{title}</h3><p className="mt-3 leading-7 text-ink-600">{text}</p></article>)}</div></section>
      <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-6xl rounded-[2.25rem] bg-sage-900 px-6 py-14 text-center text-white sm:px-12"><h2 className="text-3xl font-bold sm:text-4xl">Hôm nay, mình thử vừa sức nhé?</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-sage-100">Mất chưa đầy một phút để check-in và nhìn ngày của bạn theo một cách dịu dàng hơn.</p><Link href="/login" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 font-bold text-ink-900 hover:bg-amber-200">Dùng thử ngay <ArrowRight size={18} /></Link></div></section>
      <footer className="border-t border-sage-100 px-5 py-8 text-center text-sm text-ink-500">Hôm Nay Thế Nào? · Một khoảng nhỏ để lắng nghe mình.</footer>
    </main>
  );
}

function Preview({ time, title, energy, color }: { time: string; title: string; energy: string; color: string }) {
  return <div className="flex items-center gap-3 rounded-2xl border border-sage-100 p-3"><span className={`h-11 w-1 rounded-full ${color}`} /><span className="w-12 text-xs font-bold text-ink-500">{time}</span><span className="min-w-0 flex-1 truncate text-sm font-bold text-ink-800">{title}</span><span className="rounded-lg bg-cream-100 px-2 py-1 text-xs font-bold text-ink-700">{energy}</span></div>;
}
