import { Check, Edit3, LoaderCircle, Plus, Repeat2, SkipForward, Trash2 } from "lucide-react";
import { dateKey, formatTime, VIETNAM_TIME_ZONE, weekDays } from "@/lib/dates";
import { endOfDayEnergy, forecastActivities } from "@/lib/energy";
import { categoryLabels, statusLabels, type Activity, type DailyCheckin, type ForecastActivity } from "@/lib/types";

export function WeekView({ anchor, activities, visibleActivityIds, pendingActivityIds, checkins, defaultEnergy, now, onAdd, onComplete, onEdit, onSkip, onDelete }: { anchor: Date; activities: Activity[]; visibleActivityIds: Set<string>; pendingActivityIds: ReadonlySet<string>; checkins: DailyCheckin[]; defaultEnergy: number; now: Date; onAdd: (date: Date) => void; onComplete: (activity: ForecastActivity) => void; onEdit: (activity: Activity) => void; onSkip: (activity: Activity) => void; onDelete: (activity: Activity) => void }) {
  const today = dateKey(now); const nowIso = now.toISOString(); const days = weekDays(anchor); const keys = new Set(days.map(dateKey));
  const weekday = new Intl.DateTimeFormat("vi-VN", { weekday: "long", timeZone: VIETNAM_TIME_ZONE });
  const dayNumber = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", timeZone: VIETNAM_TIME_ZONE });
  return <div className="overflow-x-auto pb-3"><div className="grid min-w-[980px] grid-cols-7 gap-3 lg:min-w-0">{days.map((day) => {
    const key = dateKey(day); const dayActivities = activities.filter((item) => keys.has(dateKey(new Date(item.starts_at))) && dateKey(new Date(item.starts_at)) === key); const checkin = checkins.find((item) => item.checkin_date === key); const initial = checkin?.energy_level ?? defaultEnergy; const full = forecastActivities(dayActivities, initial); const forecast = full.filter((item) => visibleActivityIds.has(item.id)); const end = endOfDayEnergy(dayActivities, initial);
    return <section key={key} className={`min-h-[440px] rounded-2xl border p-3 ${key === today ? "border-sage-500 bg-sage-50/60" : key < today ? "border-sage-200 bg-white opacity-70" : "border-sage-200 bg-white"}`}><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-ink-500">{weekday.format(day)}</p><p className="mt-1 text-2xl font-bold text-ink-900">{dayNumber.format(day)}</p></div><button type="button" onClick={() => onAdd(day)} className="rounded-xl p-2 text-sage-700 hover:bg-sage-100" aria-label={`Thêm hoạt động ngày ${key}`}><Plus size={18} /></button></header><div className="my-3 rounded-xl bg-cream-100 px-2.5 py-2 text-xs"><div className="flex justify-between"><span className="text-ink-500">Cuối ngày</span><strong className={end < 30 ? "text-amber-800" : "text-sage-800"}>{end}%</strong></div><p className="mt-1 text-[10px] text-ink-400">{checkin ? `Pin thực tế ${checkin.energy_level}%` : `Chưa có trạng thái · Ước tính từ ${defaultEnergy}%`}</p></div><div className="space-y-2">{forecast.map((item) => {
      const inactive = item.status === "skipped" || item.status === "cancelled"; const completed = item.status === "completed"; const pending = pendingActivityIds.has(item.id); const past = item.ends_at < nowIso;
      return <article key={item.id} className={`rounded-xl border-l-[3px] p-2.5 shadow-sm ${inactive || past ? "border-l-sage-300 bg-sage-50 opacity-60" : completed ? "border-l-sage-600 bg-sage-50" : item.expected_impact >= 0 ? "border-l-sage-500 bg-white" : "border-l-amber-400 bg-white"}`}><button type="button" disabled={pending} onClick={() => onEdit(item)} className="w-full text-left"><div className="flex items-center gap-1 text-[11px] font-bold text-ink-500"><span>{formatTime(item.starts_at)}</span>{item.series_id && <Repeat2 size={12} />}</div><h3 className={`mt-1 text-xs font-bold leading-4 text-ink-900 ${inactive ? "line-through" : ""}`}>{item.title}</h3><p className="mt-2 text-[10px] text-ink-500">{categoryLabels[item.category]} · {item.predicted_before}→{item.predicted_after}</p>{item.status !== "scheduled" && <p className="mt-1 text-[10px] font-bold text-ink-500">{statusLabels[item.status]}</p>}</button><div className="mt-2 flex items-center justify-end gap-0.5 border-t border-sage-100 pt-1.5">{pending && <LoaderCircle className="mr-auto animate-spin text-sage-700" size={13} />}{item.status === "scheduled" && <button disabled={pending} onClick={() => onComplete(item)} className="rounded-lg p-1.5 text-sage-700 hover:bg-sage-100" aria-label={`Hoàn thành ${item.title}`}><Check size={14} /></button>}<button disabled={pending} onClick={() => onEdit(item)} className="rounded-lg p-1.5" aria-label={`Chỉnh sửa ${item.title}`}><Edit3 size={14} /></button>{item.status === "scheduled" && <button disabled={pending} onClick={() => onSkip(item)} className="rounded-lg p-1.5" aria-label={`Nghỉ ${item.title}`}><SkipForward size={14} /></button>}<button disabled={pending} onClick={() => onDelete(item)} className="rounded-lg p-1.5 text-red-700" aria-label={`Xoá ${item.title}`}><Trash2 size={14} /></button></div></article>;
    })}{!forecast.length && <p className="pt-8 text-center text-xs leading-5 text-ink-400">Chưa có hoạt động phù hợp<br />Một khoảng thở 🌿</p>}</div></section>;
  })}</div></div>;
}
